<a href="https://colab.research.google.com/github/sumayyasyeda/sumayyasyeda/blob/main/Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The first thing we want to do is import numpy.

In [ ]:
import numpy as np

Let us first define a Python list containing the ages of 6 people.

In [ ]:
ages_list = [10, 12, 18, 2, 23, 60]
print(ages_list)

[10, 12, 18, 2, 23, 60]


There are 3 main ways to instantiate a Numpy and array object. One of these is to use np.array(<collection>)

In [ ]:
ages = np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[10 12 18  2 23 60]


In [ ]:
print(ages)
print("Size:" , ages.size) #"\t" is a tab,
print("Shape:\t", ages.shape)

[10 12 18  2 23 60]
Size: 6
Shape:	 (6,)


In [ ]:
zeroArr = np.zeros(4)
print(zeroArr)

[0. 0. 0. 0.]


**Multi-dim**

Now let us define a new list containing the weights of these 6 people.

In [ ]:
weight_list = [32, 18, 26, 60, 55, 65]

Now, we define an ndarray containing all fo this information, and again print the size and shape of the array.

In [ ]:
#fetch the dimension of rows and columns-shape
people = np.array([ages_list, weight_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape) 

People:	 [[10 12 18  2 23 60]
 [32 18 26 60 55 65]]
Size:	 12
Shape:	 (2, 6)


In [ ]:
#reshape=changing the shape of an array

people = people.reshape(12,1) 
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10]
 [12]
 [18]
 [ 2]
 [23]
 [60]
 [32]
 [18]
 [26]
 [60]
 [55]
 [65]]
Size:	 12
Shape:	 (12, 1)


**Exercise**
Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

In [ ]:
array=[7,9,65,33,85,99]
D=np.array([array])
print("1dimen \t",D)



1dimen 	 [[ 7  9 65 33 85 99]]


Generate a matrix (2D numpy array) of the values:



In [ ]:
array1=np.array([[1,2,4],[2,3,0],[0,5,1]])
print(array1)


[[1 2 4]
 [2 3 0]
 [0 5 1]]


Change the dimensions of this array to another permitted shape

In [ ]:
array1 = array1.reshape(9,1)
print("array\t",array1)

array	 [[1]
 [2]
 [4]
 [2]
 [3]
 [0]
 [0]
 [5]
 [1]]


**Array Generation**
Instead of defining an array manually, we can ask numpy to do it for us.

The np.arange() method creates a range of numbers with user defined steps between each.

In [ ]:
numbers = np.arange(0, 40, 4)
numbers

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

The np.linspace() method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.

In [ ]:
five_spaced = np.linspace(0,40,9)
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40.]


The .repeat() method will repeat an object you pas a specified number of times

In [ ]:
twoArr = np.repeat(5, 10)
print(twoArr)

[5 5 5 5 5 5 5 5 5 5]


The np.eye() functions will create an identity matrix/array for us.

In [ ]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Operations**

There are many, many operations which we can perform on arrays. Below, we demonstrate a few.

What is happening in each line?

In [ ]:
numbers


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [ ]:
print("1:", 2 * numbers)
print("2:", 10 + numbers)
print("3:", numbers - 1)
print("4:", numbers/5)
print("5:", numbers **2)
print("6:", numbers < 20) #comparision operator

1: [ 0  8 16 24 32 40 48 56 64 72]
2: [10 14 18 22 26 30 34 38 42 46]
3: [-1  3  7 11 15 19 23 27 31 35]
4: [0.  0.8 1.6 2.4 3.2 4.  4.8 5.6 6.4 7.2]
5: [   0   16   64  144  256  400  576  784 1024 1296]
6: [ True  True  True  True  True False False False False False]


Speed Test

If we compare the speed at which we can do these operations compared to core python, we will notice a substantial difference.

In [ ]:
speed = list(range(0,6001,5))
speed

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [ ]:
speedtest = np.arange(0,5001,5)
speedtest

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [ ]:
%timeit speedtest + 5 # time a particular piece of code 

1.36 µs ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
%timeit [e + 5 for e in speed]

71.6 µs ± 511 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Boolean string operations can also be performed on ndarrays.

In [ ]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

**Transpose**

In [ ]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[10 12 18  2 23 60]
 [32 18 26 60 55 65]] 

[[10 32]
 [12 18]
 [18 26]
 [ 2 60]
 [23 55]
 [60 65]]


Data **Types**

As previously mentioned, ndarrays can only have one data type. If we want to obtain or change this, we use the .dtype attribute.

In [ ]:
people.dtype

dtype('int64')

In [ ]:
#union 21 characters---u21
strings = np.array([10, 5, 8, '32', '65', '43'])
strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

In [ ]:
#What is the dtype of this array?
strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

In [ ]:
strings = np.array([10, 5, 8, '32', '65', '43'])
print(strings)

['10' '5' '8' '32' '65' '43']


In [ ]:
strings.dtype = 'int32'
print(strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [ ]:
strings.size


126

In [ ]:
#126/21
strings.size/21

6.0

In [ ]:
np.array([10, 5, 8, '32', '65', '43']).size

6

The correct way to have changed the data type of the ndarray would have been to use the .astype() method, demonstrated below.

In [ ]:
strings = np.array([10, 5, 8, '32', '65', '43'])
print(strings)
print(strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


**Exercise**

#### Create an array of string numbers, but use dtype to make it an array of floats.

In [ ]:
strings = np.array([10, 5, 8, '32', '65', '43'])
print(strings)
print(strings.astype('float'))

['10' '5' '8' '32' '65' '43']
[10.  5.  8. 32. 65. 43.]


In [ ]:
strings = np.array([10, 5, 8, '32', '65', '43'], dtype='float')
strings

array([10.,  5.,  8., 32., 65., 43.])

#### Transpose the matrix, printing the new size and shape.

In [ ]:
number1=[1,2,3,4]
number2=[5,6,7,8]
matrix=np.array([number1,number2])

print("matrix:",matrix)
print("transpose",matrix.T)


print("size:",matrix.T.size)
print("shape:",matrix.T.shape)

matrix: [[1 2 3 4]
 [5 6 7 8]]
transpose [[1 5]
 [2 6]
 [3 7]
 [4 8]]
size: 8
shape: (4, 2)


#### Use the .astype() method to convert the array to boolean.

In [ ]:
array = np.array([1,0,2,3,4,5,6])
print(array)
#print(strings.astype('float'))
usingastype=array.astype(dtype=bool)
print(f" boolean array is:{usingastype}")

[1 0 2 3 4 5 6]
 boolean array is:[ True False  True  True  True  True  True]


**Array Slicing Operations**

As before, we can use square brackets and indices to access individual values, and the colon operator to slice the array.

In [ ]:
numbers

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [ ]:
numbers[0]

0

In [ ]:
numbers[-1]

36

In [ ]:
numbers[:4]

array([ 0,  4,  8, 12])

In [ ]:
numbers[4:]

array([16, 20, 24, 28, 32, 36])

In [ ]:
#We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

print(people)
people[:3,:3]

[[10 12 18  2 23 60]
 [32 18 26 60 55 65]]


array([[10, 12, 18],
       [32, 18, 26]])

Exercise

Create a numpy array with 50 zeros

In [ ]:
number3=np.zeros((50), dtype=int)
print(number3)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]


Create a np array of 2 repeated 20 times

In [ ]:
number4=np.repeat(2,20)
number4

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Create a numpy array from 0 to 2pi  in steps of 0.1

In [ ]:
import math as m
arr=np.arange(0,m.pi*2,0.1)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])


For one of the arrays generated:

Get the first five values
Get the last 3 values
Get the 4th value to the 7th value

In [ ]:
#Get the first five values
array2=[2,3,4,5,6,7,6,78,9]
array2[:6]


[6, 7, 6, 78, 9]

In [ ]:
#Get the last 3 values
array2[6:]

[6, 78, 9]

In [ ]:
#Get the 4th value to the 7th value

array2[4:8]

[6, 7, 6, 78]

We can reverse an array by using .flip() or by using the :: operator.

In [ ]:
numbers=np.flip(numbers)

numbers

array([36, 32, 28, 24, 20, 16, 12,  8,  4,  0])

In [ ]:
reversenumbers=numbers[-1::-1]
print(numbers)
print(reversenumbers)

[36 32 28 24 20 16 12  8  4  0]
[ 0  4  8 12 16 20 24 28 32 36]


We can also use the :: operator to select steps of the original array.

In [ ]:
numbers[0::3]

array([36, 24, 12,  0])

Exercise

take one of the arrays you defined and

#### Reverse it

In [ ]:
num=[1,23,4,56,67,3]
num1=np.flip(num)
num1

array([ 3, 67, 56,  4, 23,  1])

Only keep every 4th element.

In [ ]:
num[::4]

[1, 67]

#### Get every 2nd element, starting from the last and moving backwards.

In [ ]:
num1[::2][::-1]

array([23, 56,  3])

Stats

In [ ]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [ ]:
nums = np.arange(0, 4, 0.2555)
nums

array([0.    , 0.2555, 0.511 , 0.7665, 1.022 , 1.2775, 1.533 , 1.7885,
       2.044 , 2.2995, 2.555 , 2.8105, 3.066 , 3.3215, 3.577 , 3.8325])

Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [ ]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))#sum/total
print("median = ", np.median(nums).round(2))#numof value+1/2
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


**Random**

With np.random, we can generate a number of types of dataset, and create training data.

The below code simulates a fair coin toss.

In [ ]:
flip = np.random.choice([0,1], 10)
flip

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
np.random.rand(10,20,9)

array([[[0.1374034 , 0.85605999, 0.29339844, ..., 0.64383782,
         0.50847221, 0.78990035],
        [0.39886482, 0.28232812, 0.74123453, ..., 0.26582234,
         0.10155454, 0.86320254],
        [0.42019487, 0.71591916, 0.14798638, ..., 0.98189809,
         0.31610399, 0.57544799],
        ...,
        [0.24257642, 0.69048082, 0.93669459, ..., 0.84241711,
         0.02338359, 0.88523826],
        [0.63564278, 0.89277977, 0.14949448, ..., 0.03249512,
         0.76045774, 0.14442944],
        [0.72779191, 0.72041472, 0.48513294, ..., 0.93038648,
         0.18631387, 0.59688345]],

       [[0.59814785, 0.25619734, 0.48747136, ..., 0.89731895,
         0.80792012, 0.03696909],
        [0.56726996, 0.25556254, 0.85885798, ..., 0.90546884,
         0.18639314, 0.32431493],
        [0.79203093, 0.81391006, 0.66921735, ..., 0.10927355,
         0.67823067, 0.09778866],
        ...,
        [0.07915532, 0.97021534, 0.6788185 , ..., 0.62435569,
         0.53507751, 0.01165873],
        [0.0

We can produce 1000 datapoints of a normally distributed data set by using np.random.normal()

In [ ]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)
s

array([-4.54902587e-02, -1.52070155e-01, -6.60983079e-02, -7.06598220e-02,
       -1.13118215e-01, -8.00469699e-03,  6.82373483e-02,  3.53116735e-02,
        5.95068252e-02,  1.24998247e-02,  7.06843786e-02,  8.11931186e-02,
        4.90278710e-02, -1.36415549e-01,  1.22179902e-01,  1.05196174e-01,
        5.02899839e-02, -8.48974303e-02,  5.56934908e-02,  9.86729306e-02,
       -7.52980321e-02, -1.85675320e-02, -4.82034198e-02,  1.25372047e-02,
       -5.01557583e-02,  3.75052767e-02,  8.54109161e-02,  8.76607566e-02,
        2.61070781e-02,  1.85167704e-01,  1.00552784e-01, -6.10082877e-02,
        7.69471199e-02, -1.62229529e-01,  7.40850634e-02,  1.34197261e-01,
        3.30625248e-02, -1.36570441e-02, -1.60263937e-01, -7.54281487e-02,
        1.78260858e-02,  1.84525402e-01, -1.40083648e-02,  1.36378992e-01,
       -3.37456614e-02, -5.72877661e-02,  1.54593458e-01, -3.96509551e-02,
        1.18827577e-01, -9.31886228e-02,  6.83180979e-02,  1.21734874e-01,
        5.89009469e-02, -

Exercise
Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.

In [ ]:
coin = np.random.choice([1,2,3,4,5,6],10)
coin

array([2, 1, 1, 3, 5, 2, 1, 2, 1, 1])

Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.

In [ ]:
coin=np.random.choice(['head','head','tail'],2)
coin

array(['head', 'head'], dtype='<U4')